### ISSUE TITLE
SPAサイトで起こる評価表示エレメントの増殖バグ

### ISSUE THREAD

**Issue by nishikawa-ryu** [benjaaamin0518/site-rating-kun#1]
SPA(Twitter等)のサイトにて評価をヘッダーに表示するエレメントが更新するたびに増殖するバグを治したい。

**Comment by nishikawa-r** [comment]
https://github.com/benjaaamin0518/site-rating-kun/blob/02900f9f9115ab9ee9893d849e2065daf64aca50/content_script.js#L518
https://github.com/benjaaamin0518/site-rating-kun/blob/02900f9f9115ab9ee9893d849e2065daf64aca50/content_script.js#L561

これらの追加によりエレメントが削除されるので増殖バグは消えた....と思う。
